server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Importante para que funcione el enrutamiento de la SPA de Flutter Web
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché opcional para estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|json)$ {
        expires max;
        add_header Cache-Control "public";
    }
}
